### ISSUE TITLE
Placing archaic lights into archaic walls creates a golem.

### ISSUE THREAD

**Issue by Ketrai** [MysticMods/Embers#41]
Heya! Enjoy the mod, but I have one small gripe. Because the golems are created by placing two archaic brick blocks, and then an archaic light on top, you can't build brick walls with lamps in them. The golem also immediately becomes hostile rather than being neutral or anything, which is weird given the player just created them.

Could this be changed? It'd be nice not to have to worry about stacking two brick blocks and a lamp whilst building with the otherwise awesome ember's brick blocks.

**Comment by majijn** [comment]
dont place the light last? they're like vanilla iron constructs, they only form if their head is the last block placed

**Comment by duely** [comment]
Which version of Embers is this in regards to? I don't recall which of them allows you to make golems, but Embers 1 is currently unsupported. If you're using Embers Rekindled, [it has a separate issue tracker here](https://github.com/DaedalusGame/EmbersRekindled/issues).

**Comment by Ketrai** [comment]
Oh, good to know it's fine if I place the lamps first. And I believe it's rekindled? Not sure.
